// <auto-generated />
using Guitar_LMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Guitar_LMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Guitar_LMS.Models.GuitarPracticeCard", b =>
                {
                    b.Property<string>("DateStr")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Summary");

                    b.HasKey("DateStr");

                    b.ToTable("GuitarPracticeCards");
                });

            modelBuilder.Entity("Guitar_LMS.Models.TodoListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DurationInMinute");

                    b.Property<string>("GuitarPracticeCardDateStr");

                    b.Property<bool>("IsDone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("GuitarPracticeCardDateStr");

                    b.ToTable("TodoListItems");
                });

            modelBuilder.Entity("Guitar_LMS.Models.TodoListItem", b =>
                {
                    b.HasOne("Guitar_LMS.Models.GuitarPracticeCard")
                        .WithMany("TodoList")
                        .HasForeignKey("GuitarPracticeCardDateStr")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
